# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/10_Vivado/tank_war/FPGA_TankWar/FPGA_TankWar.srcs/sources_1/ip/blk_mem_gen_02/blk_mem_gen_02.xci
# IP: The module: 'blk_mem_gen_02' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/10_Vivado/tank_war/FPGA_TankWar/FPGA_TankWar.gen/sources_1/ip/blk_mem_gen_02/blk_mem_gen_02_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_02'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/10_Vivado/tank_war/FPGA_TankWar/FPGA_TankWar.srcs/sources_1/ip/blk_mem_gen_02/blk_mem_gen_02.xci
# IP: The module: 'blk_mem_gen_02' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/10_Vivado/tank_war/FPGA_TankWar/FPGA_TankWar.gen/sources_1/ip/blk_mem_gen_02/blk_mem_gen_02_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_02'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
